### ISSUE TITLE
Update the raw swagger file

### ISSUE THREAD

**Issue by pramodvallanur** [ibm-apiconnect/getting-started#15]
Issue is for https://github.com/ibm-apiconnect/getting-started/tree/master/bluemix/1a
Skip this step- Update the source swagger file to have either $(catalog.host) already in it or just the exclude the host field in the file. I know this affects other tutorials. But i have provided same comment to Zach tutorial as well.

If you are removing this step, then there is no need of Save action that follows this

**Comment by deeyas** [comment]
@pramodvallanur pls help me understand the motivation behind this recommendation.

I set it up this way to mimic customer env., i.e. when they import their existing swagger, it'll have their specific hostname/addr. And they would have to change it. So updating to ($catalog.host) provides a good product touchpoint IMO.

Leaving the host field blank would work, but is confusing because the host field is marked as a required field '*' (which cannot/should not) be blank.

@Zach-Guilfoyle this impacts your write-up as well.

**Comment by pramodvallanur** [comment]
Thats not true, the swagger you are importing is not a general market available swagger like pet store, but already customized IBM API Connect swagger.

**Comment by deeyas** [comment]
Yes, in this tutorial users are importing IBM customized swagger. So having $(catalog.host) makes sense, and I will update the swagger.

My comment was -- outside this tutorial, customers may be importing their own swagger that is not IBM customized, and then will have to update the host. Doing so in this tutorial will just help them see what to do outside the tutorial.
