### ISSUE TITLE
Remove Invoke & substitute with Proxy in the API Definition

### ISSUE THREAD

**Issue by pramodvallanur** [ibm-apiconnect/getting-started#16]
Issue is for https://github.com/ibm-apiconnect/getting-started/tree/master/bluemix/1a

Pls see the comment i had provided to Zach which i had forwarded to you. Please remove invoke activity and replace it with proxy.

Comment i gave to Zach was:
'i saw the swagger, the tutorial is around proxy, but we use invoke activity, lets use proxy activity instead. Also if you can, you can reduce the backend weather service just to be one api- either current or forecast to make it more simpler. if you are using only one weather endpoints, then in your proxy, you can provide the endpoint directly similar to how you have done in your invoke activity if not you need to provide something like this so that it can handle both current & forecast- https://myweatherprovider.mybluemix.net$(request.path)$(request.search)'

**Comment by deeyas** [comment]
- **About using invoke Vs proxy**
  - wouldn't invoke be more appropriate here since we are invoking an existing service? 
  - Vs using proxy which would be used when invoking a proxy API
  ***

- **Using just one path (either current or forecast)**
  - I am okay with this; just want to get @lana-li  and @newtonpiccone1 to weigh in since they designed the user story
  ***   

- **endpoint URL ― good catch** :)
  - the instructions are to update the URL field to https:// myweatherprovider.mybluemix.net/today?zipcode=$(request.parameters.zipcode)
  - at least in the 1b content. Need to update this in the swagger file that we ask users to import

@Zach-Guilfoyle FYI this may impact your write-up

**Comment by pramodvallanur** [comment]
a] Proxy activity will be used and can be used only once in the assembly flow, as it is a pass-through.
b] Invoke activity can be used instead, but typically used when you have to invoke more than one service in the assembly
c] My understanding the getting started topic was proxy to an existing service and having a proxy activity would be appropriate

**Comment by lana-li** [comment]
@pramodvallanur regarding using either current or forecast: let's keep it as is for now. it's already fairly simple. we need to stay strictly on schedule; don't want to spend additional time changing the backend and then seeing what details may need to change elsewhere

**Comment by pramodvallanur** [comment]
i am ok, if that the story we are building. I dont agree its fairly simple. To get started, users dont need to understand switch activities etc. All they need is a proxy activity in the assembly. As i said there is no need to change anything in the backend service to restrict it to a single path.
