### ISSUE TITLE
Restrict to one path

### ISSUE THREAD

**Issue by pramodvallanur** [ibm-apiconnect/getting-started#30]
Issue is for : https://github.com/ibm-apiconnect/getting-started/blob/master/bluemix/1b/README.md

My recommendation is that we should restrict this tutorial to just adding only one path. Adding both today & current is kind of lengthy, possibly you could provide it as twisty or an extension

**Comment by deeyas** [comment]
@lana-li @newtonpiccone1 
Please see Pramodh's recommendation about just handling one path Vs /today and /current.
How will this change the story you are building?
Also, changing to 1 path at this time would require clean up work including new screenshots

**Comment by pramodvallanur** [comment]
@deeyas not sure i follow the screen shot comment, i dont see any particular possibly a coupe that references /today.

The above issue was if the tutorial is around getting started, should we just stick to the simplest and easiest of what needs to get done

**Comment by deeyas** [comment]
@pramodvallanur I see your POV about keeping it simple for getting-started, i.e. just restrict to one path. 

By "new screenshots", I mean we _might_ have to update any screenshot that shows both paths; not only in this particular tutorial, but also others that build on this (e.g. rate limiting, security, etc).

I'm okay either way, but leaving that up to @newtonpiccone1 and @lana-li since they're writing the end-to-end user story.

**Comment by deeyas** [comment]
Assigning @lana-li and @newtonpiccone1 to weigh in and decide whether to restrict to one path.

**Comment by newtonpiccone1** [comment]
@lana-li this is all you. @deeyas I have been taken off getting started strategy and am now a tutorial author

**Comment by lana-li** [comment]
see comment here: https://github.com/ibm-apiconnect/getting-started/issues/16#issuecomment-308561433
