### ISSUE TITLE
Rate-limiting: Delete the dev portal aspects - they are not covered until a later Getting started

### ISSUE THREAD

**Issue by rgthelen** [ibm-apiconnect/getting-started#6]
Rate-limiting: Suggest Deleting the dev portal aspects - they are not covered until a later Getting started.

**Comment by sunitajennings** [comment]
So, rate-limiting without dev portal interaction is problematic. Rate limits aren't respected when using the provided test app/client id. Therefore, a user will need to create an application in order to see their rate limits in effect.

(From https://www.ibm.com/support/knowledgecenter/en/SSMNED_5.0.0/com.ibm.apic.toolkit.doc/capim_products.html "The test application that is used by the API Manager test tool is not subject to rate limits if you have enabled automatic subscriptions for the Catalog in which you are testing."
